---

- name: "stat {{ raspy_sd_boot }}"
  stat:
    path: "{{ raspy_sd_boot }}"
  register: boot

- name: "stat {{ raspy_sd_rootfs }}"
  stat:
    path: "{{ raspy_sd_rootfs }}"
  register: rootfs

- name: enable ssh
  template:
    src: ssh.j2
    dest: "{{ raspy_sd_boot }}/ssh"
  when: boot.stat.islnk is defined

- name: enable wifi
  template:
    src: wpa_supplicant.conf.j2
    dest: "{{ raspy_sd_boot }}/wpa_supplicant.conf"
  when: boot.stat.islnk is defined

- name: create ssh user directory
  file:
    path: "{{ raspy_sd_rootfs }}/home/{{ raspy_admin_user }}/.ssh"
    state: directory
    mode: 0700
  when: rootfs.stat.islnk is defined

- name: add public key to authorized keys
  copy:
    dest: "{{ raspy_sd_rootfs }}/home/{{ raspy_admin_user }}/.ssh/authorized_keys"
    content: "{{ raspy_admin_authorized_key }}"
    mode: 0600
  when: rootfs.stat.islnk is defined

- name: Disallow password authentication
  become: true
  become_method: sudo
  lineinfile:
    dest: "{{ raspy_sd_rootfs }}/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  when: rootfs.stat.islnk is defined

- name: set raspy hostname
  become: true
  become_method: sudo
  copy:
    dest: "{{ raspy_sd_rootfs }}/etc/hostname"
    content: "{{ raspy_hostname }}"
    mode: 0644
  when: rootfs.stat.islnk is defined

- name: Add hostname in hosts file
  become: true
  become_method: sudo
  replace:
    path: /etc/hosts
    regexp: '(\s+)raspberrypi(\s+.*)?$'
    replace: "'\1{{ raspy_hostname }}\2'"

  lineinfile:
    dest: "{{ raspy_sd_rootfs }}/etc/hosts"
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ raspy_hostname }}"
    state: present
  when: rootfs.stat.islnk is defined

- name: dhcp config for static ip
  become: true
  become_method: sudo
  template:
    src: dhcpcd.conf.j2
    dest: "{{ raspy_sd_rootfs }}/etc/dhcpcd.conf"
  when: rootfs.stat.islnk is defined
