---

- name: download docker install script
  get_url:
    url: "https://get.docker.com"
    dest: /tmp/install_docker.sh
    validate_certs: no
    force: yes
    mode: 0744

- name: install docker, the easy way
  shell: /tmp/install_docker.sh

- name: add pi user to docker group
  user:
    name: "{{ raspy_admin_user }}"
    groups: docker
    append: yes
